version: '3.8'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:        
  db-data:  

  